unumero = int(input('digite o primeiro número: '))
dnumero = int(input('digite o segundo número: '))
print(f'A soma é igual {unumero + dnumero}')
print(f'A subtração é igual {unumero - dnumero}')
print(f'A multiplicação é igual {unumero * dnumero}')
print(f'A divisão é igual {unumero / dnumero}')
